### ISSUE TITLE
Zip is overwritten if not moved from output folder if porthelper is run again. (WinGUI)

### ISSUE THREAD

**Issue by Jesright73** [Miepee/AM2RPortHelper#4]
To repeat:

1. Choose a mod.
2. select output type
3. click `Port!`
4. Leave zip folder in output location.
5. Repeat 1-3.
6. Observe that the zip folder from the first run has been overwritten by the newly produced zip.
7. Submit issue to Miepee.

OS: Windows 10 64-bit 21H1
Porthelper version: Windows GUI 1.3.2

**Comment by Miepee** [comment]
Seems like intended behaviour for me, what result did you expect?

**Comment by Jesright73** [comment]
Expected output files with different names to not be overwritten, like with the earlier versions of of Port Helper.

**Comment by Miepee** [comment]
Can you define *which* earlier version it was that had a different behaviour? As far as I remember, it always used to overwrite.

Also, when you say "repeat 1-3" do you mean that a different mod was chosen? or the same one as before?

**Comment by Miepee** [comment]
Oh I see what you mean now.
The repro steps are:
1. choose one mod
2. select an output type
3. port
4. select a different output type that was chosen in 2
5. port

**Comment by Jesright73** [comment]
> Can you define which earlier version it was that had a different behaviour? As far as I remember, it always used to overwrite.

it was version 1.2.
