### ISSUE TITLE
Crash when attempting to port non-AM2R game with recent commits

### ISSUE THREAD

**Issue by Jesright73** [Miepee/AM2RPortHelper#7]
Recent Port Helper builds crash when attempting to port a non-AM2R game

In this example, i selected the Horde Server and attempted to port to Linux. 

OS: Windows 10
Encountered with Port Helper Version: Build 68, Commit https://github.com/Miepee/AM2RPortHelper/commit/824e19ebb2f0a87f5ae50ab4894f233a94bde2cf

Port Helper Release 1.3.2 is able to successfully port to Linux.

**Comment by Miepee** [comment]
Can you upload the zip that you used?

**Comment by Miepee** [comment]
Nevermind, found the issue.
